import { useQuery } from '@tanstack/react-query';
import { BarChart3 } from 'lucide-react';
import { getAnalytics } from '../services/analytics.service';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { useContentTypes } from '../hooks/useContentTypes';

const STATUS_COLORS = {
  completed: 'bg-green-500',
  processing: 'bg-amber-500',
  failed: 'bg-destructive',
};

const Analytics = () => {
  const { data, isLoading, isError } = useQuery({
    queryKey: ['analytics'],
    queryFn: getAnalytics,
  });
  const { data: typesData } = useContentTypes();

  const labelFor = (typeId) => typesData?.types.find((t) => t.id === typeId)?.label || typeId;

  if (isLoading) {
    return (
      <div className="p-8 max-w-4xl mx-auto space-y-4">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-40 w-full" />
        <Skeleton className="h-40 w-full" />
      </div>
    );
  }

  if (isError) {
    return (
      <div className="p-8 max-w-4xl mx-auto">
        <p className="text-sm text-destructive">Couldn't load analytics. Please try refreshing the page.</p>
      </div>
    );
  }

  const maxContentCount = Math.max(1, ...data.contentByType.map((c) => c.count));
  const maxDayCount = Math.max(1, ...data.videosOverTime.map((d) => d.count));
  const totalVideos = data.videosByStatus.reduce((sum, s) => sum + s.count, 0);

  return (
    <div className="p-8 max-w-4xl mx-auto space-y-4">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <BarChart3 className="w-5 h-5" />
          Analytics
        </h1>
        <p className="text-muted-foreground">How you've been using VidScribe.</p>
      </div>

      {/* Status breakdown */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Videos by Status</CardTitle>
        </CardHeader>
        <CardContent>
          {totalVideos === 0 ? (
            <p className="text-sm text-muted-foreground text-center py-6">No videos processed yet.</p>
          ) : (
            <div className="space-y-3">
              <div className="flex h-3 rounded-full overflow-hidden bg-muted">
                {data.videosByStatus.map((s) => (
                  <div
                    key={s.status}
                    className={STATUS_COLORS[s.status] || 'bg-muted-foreground'}
                    style={{ width: `${(s.count / totalVideos) * 100}%` }}
                    title={`${s.status}: ${s.count}`}
                  />
                ))}
              </div>
              <div className="flex flex-wrap gap-4 text-sm">
                {data.videosByStatus.map((s) => (
                  <div key={s.status} className="flex items-center gap-1.5">
                    <span className={`w-2.5 h-2.5 rounded-full ${STATUS_COLORS[s.status] || 'bg-muted-foreground'}`} />
                    <span className="capitalize">{s.status}</span>
                    <span className="text-muted-foreground">{s.count}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Content by type */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Content Generated by Format</CardTitle>
        </CardHeader>
        <CardContent>
          {data.contentByType.length === 0 ? (
            <p className="text-sm text-muted-foreground text-center py-6">No content generated yet.</p>
          ) : (
            <div className="space-y-2">
              {data.contentByType
                .slice()
                .sort((a, b) => b.count - a.count)
                .map((c) => (
                  <div key={c.type} className="flex items-center gap-3">
                    <span className="text-sm w-36 shrink-0 truncate">{labelFor(c.type)}</span>
                    <div className="flex-1 h-2 rounded-full bg-muted overflow-hidden">
                      <div
                        className="h-full bg-primary rounded-full"
                        style={{ width: `${(c.count / maxContentCount) * 100}%` }}
                      />
                    </div>
                    <span className="text-sm text-muted-foreground w-6 text-right">{c.count}</span>
                  </div>
                ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Activity over time */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Videos Processed — Last 14 Days</CardTitle>
        </CardHeader>
        <CardContent>
          {data.videosOverTime.length === 0 ? (
            <p className="text-sm text-muted-foreground text-center py-6">No activity in the last 14 days.</p>
          ) : (
            <div className="flex items-end gap-1.5 h-28">
              {data.videosOverTime.map((d) => (
                <div key={d.date} className="flex-1 flex flex-col items-center justify-end gap-1 group relative">
                  <div className="text-xs text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity absolute -top-5">
                    {d.count}
                  </div>
                  <div
                    className="w-full bg-primary rounded-t-sm min-h-[3px]"
                    style={{ height: `${(d.count / maxDayCount) * 100}%` }}
                    title={`${d.date}: ${d.count} video(s)`}
                  />
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default Analytics;
