import { useState, useEffect, useRef } from 'react';
import { useParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Loader2, AlertCircle, ChevronDown, ChevronUp, FileText } from 'lucide-react';
import { getVideoById } from '../services/video.service';
import { useGenerateContent } from '../hooks/useGenerateContent';
import { useContentTypes } from '../hooks/useContentTypes';
import { Card, CardContent } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { useToast } from '../context/ToastContext';

import ContentCardShell from '../components/content/ContentCardShell';
import GenerationOptions from '../components/content/GenerationOptions';
import ContentPackSelector from '../components/content/ContentPackSelector';

import SummaryCard from '../components/content/SummaryCard';
import BlogCard from '../components/content/BlogCard';
import LinkedInCard from '../components/content/LinkedInCard';
import TwitterCard from '../components/content/TwitterCard';
import NotesCard from '../components/content/NotesCard';
import McqCard from '../components/content/McqCard';
import InstagramCard from '../components/content/InstagramCard';
import YoutubeDescriptionCard from '../components/content/YoutubeDescriptionCard';
import EmailCard from '../components/content/EmailCard';
import FaqCard from '../components/content/FaqCard';
import KeyTakeawaysCard from '../components/content/KeyTakeawaysCard';
import SeoPackCard from '../components/content/SeoPackCard';
import FlashcardsCard from '../components/content/FlashcardsCard';
import ActionItemsCard from '../components/content/ActionItemsCard';

const DISPLAY_COMPONENTS = {
  summary: SummaryCard,
  blog: BlogCard,
  linkedin: LinkedInCard,
  twitter: TwitterCard,
  notes: NotesCard,
  mcq: McqCard,
  instagram: InstagramCard,
  youtube_description: YoutubeDescriptionCard,
  email: EmailCard,
  faq: FaqCard,
  key_takeaways: KeyTakeawaysCard,
  seo_pack: SeoPackCard,
  flashcards: FlashcardsCard,
  action_items: ActionItemsCard,
};

const statusVariant = {
  completed: 'secondary',
  processing: 'outline',
  failed: 'destructive',
};

// Category display order for grouping the tab bar visually
const CATEGORY_ORDER = ['Repurpose', 'SEO & Marketing', 'Social Media', 'Study & Learning'];

const VideoDetail = () => {
  const { id } = useParams();
  const { showToast } = useToast();
  const queryClient = useQueryClient();
  const [params, setParams] = useState({});
  const [transcriptOpen, setTranscriptOpen] = useState(false);
  const [activeTab, setActiveTab] = useState('summary');
  const autoGenerated = useRef(false);

  // Reset the auto-generate flag whenever navigating to a different video —
  // React Router reuses this same component instance across /videos/:id
  // changes, so without this a video visited later in the session would
  // never get its automatic first-format generation.
  useEffect(() => {
    autoGenerated.current = false;
    setActiveTab('summary');
    setTranscriptOpen(false);
  }, [id]);

  const { data, isLoading, isError } = useQuery({
    queryKey: ['video', id],
    queryFn: () => getVideoById(id),
  });

  const { data: typesData } = useContentTypes();
  const { mutate: generate, isPending, variables } = useGenerateContent(id);

  const isFailedVideo = data?.video.status === 'failed';
  const isProcessing = data?.video.status === 'processing';
  const hasAnyContent = (data?.generatedContent?.length || 0) > 0;

  // First time landing on a freshly-processed video with nothing generated
  // yet: auto-generate the Summary immediately, so the page arrives with
  // real AI content instead of a blank "click Generate" prompt.
  useEffect(() => {
    if (
      data &&
      !isFailedVideo &&
      !isProcessing &&
      !hasAnyContent &&
      !autoGenerated.current &&
      !isPending
    ) {
      autoGenerated.current = true;
      generate(
        { type: 'summary', params: {} },
        {
          onError: () => {
            // Silent — the tab's own empty state still offers a manual Generate button
          },
        }
      );
    }
  }, [data, isFailedVideo, isProcessing, hasAnyContent, isPending, generate]);

  if (isLoading) {
    return (
      <div className="p-8 max-w-4xl mx-auto space-y-4">
        <Skeleton className="h-8 w-2/3" />
        <Skeleton className="h-40 w-full" />
      </div>
    );
  }

  if (isError || !data) {
    return (
      <div className="p-8 max-w-4xl mx-auto">
        <Card>
          <CardContent className="flex flex-col items-center gap-2 py-10 text-center">
            <AlertCircle className="w-6 h-6 text-destructive" />
            <p className="text-sm text-muted-foreground">
              Couldn't load this video. It may not exist, or you may not have access to it.
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  const findItem = (type) => data.generatedContent?.find((c) => c.type === type);

  const handleGenerate = (type, regenerateOption) => {
    generate(
      { type, params: regenerateOption ? { ...params, regenerateOption } : params },
      {
        onError: (err) => {
          showToast(err.response?.data?.message || `Failed to generate ${type}`, 'error');
        },
      }
    );
  };

  const types = (typesData?.types || [])
    .slice()
    .sort((a, b) => CATEGORY_ORDER.indexOf(a.categoryLabel) - CATEGORY_ORDER.indexOf(b.categoryLabel));

  return (
    <div className="p-8 max-w-4xl mx-auto space-y-4">
      {/* Header */}
      <div>
        <h1 className="text-xl font-bold truncate">{data.video.youtubeUrl}</h1>
        <div className="flex items-center gap-2 mt-1">
          <Badge variant={statusVariant[data.video.status] || 'outline'}>{data.video.status}</Badge>
          <p className="text-sm text-muted-foreground">{data.video.wordCount} words in transcript</p>
        </div>
      </div>

      {isFailedVideo && (
        <Card>
          <CardContent className="py-4 text-sm text-destructive flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            This video's transcript could not be retrieved (captions may be disabled or unavailable).
            Content generation isn't possible for this video.
          </CardContent>
        </Card>
      )}

      {isProcessing && (
        <Card>
          <CardContent className="py-4 text-sm text-muted-foreground flex items-center gap-2">
            <Loader2 className="w-4 h-4 animate-spin shrink-0" />
            This video is still processing. Refresh in a moment.
          </CardContent>
        </Card>
      )}

      {/* Collapsible transcript — out of the way by default, one click away */}
      {!isFailedVideo && !isProcessing && (
        <div>
          <button
            onClick={() => setTranscriptOpen((o) => !o)}
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <FileText className="w-3.5 h-3.5" />
            {transcriptOpen ? 'Hide transcript' : 'View transcript'}
            {transcriptOpen ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
          </button>
          {transcriptOpen && (
            <Card className="mt-2">
              <CardContent className="pt-6">
                <p className="text-sm whitespace-pre-wrap max-h-64 overflow-y-auto text-left text-muted-foreground">
                  {data.transcript?.rawText}
                </p>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {/* Single unified generation area: options bar, tabs with a pack
          action, and one result card — no duplicated format lists. */}
      {!isFailedVideo && !isProcessing && (
        <Card className="py-0 overflow-hidden">
          <div className="px-4">
            <GenerationOptions params={params} onChange={setParams} />
          </div>

          <Tabs value={activeTab} onValueChange={setActiveTab}>
            <div className="flex items-center justify-between gap-2 px-4 pt-3 flex-wrap">
              <div>
                <p className="text-xs font-medium text-muted-foreground mb-1.5">Choose a format</p>
                <TabsList className="flex-wrap h-auto bg-transparent p-0 gap-1 justify-start">
                  {types.map(({ id: typeId, label }) => {
                    const generated = !!findItem(typeId);
                    return (
                      <TabsTrigger
                        key={typeId}
                        value={typeId}
                        className="data-[state=active]:bg-secondary data-[state=active]:shadow-none border"
                      >
                        {label}
                        {generated && <span className="w-1.5 h-1.5 rounded-full bg-primary ml-1.5" />}
                      </TabsTrigger>
                    );
                  })}
                </TabsList>
              </div>
              <ContentPackSelector videoId={id} params={params} />
            </div>

            {types.map(({ id: typeId, label }) => {
              const item = findItem(typeId);
              const isGeneratingThis = isPending && variables?.type === typeId;
              const DisplayComponent = DISPLAY_COMPONENTS[typeId];

              return (
                <TabsContent key={typeId} value={typeId} className="p-4 pt-3">
                  <ContentCardShell
                    type={typeId}
                    label={label}
                    videoId={id}
                    item={item}
                    DisplayComponent={DisplayComponent}
                    isGenerating={isGeneratingThis}
                    onGenerate={(regenerateOption) => handleGenerate(typeId, regenerateOption)}
                    onSaved={() => queryClient.invalidateQueries({ queryKey: ['video', id] })}
                    bare
                  />
                </TabsContent>
              );
            })}
          </Tabs>
        </Card>
      )}
    </div>
  );
};

export default VideoDetail;
